# Generated by Django 2.2 on 2020-07-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_address', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в blacklist')),
            ],
            options={
                'verbose_name': 'Blacklist по IP',
                'verbose_name_plural': 'Blacklists по IP',
            },
        ),
        migrations.CreateModel(
            name='CountForIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=250, verbose_name='Регистрация страницы')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Регистрация времени')),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Cчетчик по IP',
                'verbose_name_plural': 'Cчетчики по IP',
                'ordering': ['-time'],
            },
        ),
    ]
