# Generated by Django 2.2 on 2020-07-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('address', models.CharField(help_text='улица, дом (аппартаменты)', max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Итого')),
                ('order_notes', models.TextField(verbose_name='Примечание к заказу')),
                ('delivery', models.CharField(choices=[('SERVICE', 'Службой доставки'), ('PICKUP', 'Самовывовозом из магазина')], default='SERVICE', max_length=7, verbose_name='Способ забора товара')),
                ('method_paid', models.CharField(choices=[('CASH', 'Наличными при получении'), ('ONLINE', 'Онлайн, картой на сайте'), ('INVOICE', 'Счет, банковским платежом')], default='ONLINE', max_length=7, verbose_name='Метод оплаты')),
                ('order_ispaid', models.BooleanField(default=False, verbose_name='Стату оплаты заказа')),
                ('order_status', models.CharField(default='WAIT', max_length=9, verbose_name='Статус заказа')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_and_clients.Cart')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_and_clients.Client')),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_and_clients.ShippingAddress', verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='shipping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_and_clients.ShippingAddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quentity', models.IntegerField(verbose_name='Количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='card_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_and_clients.CartItem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales_and_clients.Client'),
        ),
    ]
