# Generated by Django 2.2 on 2020-08-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
