# Generated by Django 2.2 on 2020-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessbot',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username telegram')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name in telegram')),
            ],
            options={
                'verbose_name': 'Chat for notificate',
                'verbose_name_plural': 'Chats for notificate',
            },
        ),
    ]
