# Generated by Django 2.2 on 2020-07-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200724_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typearticle',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.TypeArticle'),
            preserve_default=False,
        ),
    ]
