# Generated by Django 2.2 on 2020-08-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200724_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/blog/%Y/%m/$d', verbose_name='Cover post'),
        ),
    ]
