# Generated by Django 2.2 on 2020-08-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='q_and_a.Question', verbose_name='Вопрос'),
        ),
    ]
